server:
  port: 9095

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/talent-sphere-personel-db
    username: talent-sphere
    password: ts123456

  jpa:
    hibernate:
      ddl-auto: create