package org.group3.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.group3.constant.ErrorMessages.*;

@Getter
@AllArgsConstructor
public enum ErrorType {

    INTERNAL_ERROR_SERVER(97500, INTERNAL_ERROR_SERVER_ERROR_MESSAGES, HttpStatus.INTERNAL_SERVER_ERROR),
    PARAMETER_NOT_VALID(97008, PARAMETER_NOT_VALID_ERROR_MESSAGES, HttpStatus.BAD_REQUEST),
    COMPANY_NOT_ACTIVE(97024, COMPANY_NOT_ACTIVE_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    COMPANY_NOT_FOUND(97025, COMPANY_NOT_FOUND_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    PAYMENT_ALREADY_EXISTS(97026, PAYMENT_ALREADY_EXISTS_ERROR_MESSAGES, HttpStatus.BAD_REQUEST),
    PERSONAL_ALREADY_EXISTS(97027, PERSONAL_ALREADY_EXISTS_ERROR_MESSAGES, HttpStatus.BAD_REQUEST),
    HOLIDAY_ALREADY_EXISTS(97028, HOLIDAY_ALREADY_EXISTS_ERROR_MESSAGES, HttpStatus.BAD_REQUEST),
    BREAK_NOT_ACTIVE(97029, BREAK_NOT_ACTIVE_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    BREAK_NOT_FOUND(97030, BREAK_NOT_FOUND_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    COMMUNICATION_NOT_ACTIVE(97031, COMMUNICATION_NOT_ACTIVE_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    COMMUNICATION_NOT_FOUND(97032, COMMUNICATION_NOT_FOUND_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    SHIFT_NOT_ACTIVE(97033, SHIFT_NOT_ACTIVE_ERROR_MESSAGES, HttpStatus.NOT_FOUND),
    SHIFT_NOT_FOUND(97034, SHIFT_NOT_FOUND_ERROR_MESSAGES, HttpStatus.NOT_FOUND);


    private final int code;
    private final String message;
    final HttpStatus httpStatus;

}
