server:
  port: 9091

spring:
  #  security:
  #    user:
  #      name: java12
  #      password: 1234
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9092
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
        #        - id: swagger-auth-redirect
        #          uri: http://localhost:9092
        #          predicates:
        #            - Path=/auth/swagger/**
        #          filters:
        #            - name: RewritePath
        #              args:
        #                regexp: /auth/swagger/(.+)
        #                replacement: /$1

        - id: admin-service
          uri: http://localhost:9093
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminCircuitBreaker
                fallbackUri: forward:/fallback/admin

        - id: manager-service
          uri: http://localhost:9094
          predicates:
            - Path=/manager/**
          filters:
            - name: CircuitBreaker
              args:
                name: managerCircuitBreaker
                fallbackUri: forward:/fallback/manager

        - id: personal-service
          uri: http://localhost:9095
          predicates:
            - Path=/personal/**
          filters:
            - name: CircuitBreaker
              args:
                name: personalCircuitBreaker
                fallbackUri: forward:/fallback/personal

        - id: visitor-service
          uri: http://localhost:9096
          predicates:
            - Path=/visitor/**
          filters:
            - name: CircuitBreaker
              args:
                name: visitorCircuitBreaker
                fallbackUri: forward:/fallback/visitor

        - id: company-service-company
          uri: http://localhost:9097
          predicates:
            - Path=/company/**
          filters:
            - name: CircuitBreaker
              args:
                name: companyCircuitBreaker
                fallbackUri: forward:/fallback/company

        - id: company-service-shift
          uri: http://localhost:9097
          predicates:
            - Path=/shift/**
          filters:
            - name: CircuitBreaker
              args:
                name: shiftCircuitBreaker
                fallbackUri: forward:/fallback/shift

        - id: company-service-communication
          uri: http://localhost:9097
          predicates:
            - Path=/communication/**
          filters:
            - name: CircuitBreaker
              args:
                name: communicationCircuitBreaker
                fallbackUri: forward:/fallback/communication

        - id: company-service-break
          uri: http://localhost:9097
          predicates:
            - Path=/break/**
          filters:
            - name: CircuitBreaker
              args:
                name: breakCircuitBreaker
                fallbackUri: forward:/fallback/break

        - id: payment-service
          uri: http://localhost:9098
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment

        - id: holiday-service
          uri: http://localhost:9101
          predicates:
            - Path=/holiday/**
          filters:
            - name: CircuitBreaker
              args:
                name: holidayCircuitBreaker
                fallbackUri: forward:/fallback/holiday

        - id: comment-service
          uri: http://localhost:9102
          predicates:
            - Path=/comment/**
          filters:
            - name: CircuitBreaker
              args:
                name: commentCircuitBreaker
                fallbackUri: forward:/fallback/comment


secrets:
  secret-key: ${TALENTSPHERE_SECRETKEY}
  issuer: ${TALENTSPHERE_ISSUER}



