server:
  port: 9102

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/TalentSphereComment
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

apiGatewayUrl: "http://localhost:9091"