package org.group3.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.group3.constant.ErrorMessages.*;

@Getter
@AllArgsConstructor
public enum ErrorType {


    INTERNAL_ERROR_SERVER(92500,INTERNAL_ERROR_SERVER_ERROR_MESSAGES,HttpStatus.INTERNAL_SERVER_ERROR),

    REGISTER_EMAIL_ALREADY_EXISTS(92001,REGISTER_EMAIL_ALREADY_EXISTS_ERROR_MESSAGES,HttpStatus.BAD_REQUEST),

    TOKEN_NOT_CREATED(92002,TOKEN_NOT_CREATED_ERROR_MESSAGES,HttpStatus.BAD_REQUEST),

    USER_NOT_FOUND(92003,USER_NOT_FOUND_ERROR_MESSAGES,HttpStatus.NOT_FOUND),

    USER_ALREADY_DELETED(92004,USER_ALREADY_DELETED_ERROR_MESSAGES,HttpStatus.BAD_REQUEST),

    ID_NOT_FOUND(92005,ID_NOT_FOUND_ERROR_MESSAGES,HttpStatus.NOT_FOUND),

    ACCOUNT_NOT_ACTIVE(92006,ACCOUNT_NOT_ACTIVE_ERROR_MESSAGES,HttpStatus.FORBIDDEN),

    REGISTER_PASSWORD_MISMATCH(92007,REGISTER_PASSWORD_MISMATCH_ERROR_MESSAGES,HttpStatus.BAD_REQUEST),

    PARAMETER_NOT_VALID(92008,PARAMETER_NOT_VALID_ERROR_MESSAGES,HttpStatus.BAD_REQUEST);

    private final int code;
    private final String message;
    final HttpStatus httpStatus;
}
